language: minimal
services:
- docker

if: branch = master

before_install:
  - openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in settings.json.enc -out settings.json -d
  - export VERSION=$(cat VERSION)
before_script:
  - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_TOKEN
script:
  - docker build -t $DOCKERHUB_REPO:latest -t $DOCKERHUB_REPO:$VERSION
after_success:
  - docker push $DOCKERHUB_REPO:latest
  - docker push $DOCKERHUB_REPO:$VERSION